import React, { useEffect, useRef, useState } from "react";
import root from "react-shadow";

// Compiled Tailwind + base styles, imported as a raw string so we can inject
// it as a <style> tag *inside* the shadow root. Generated by `npm run build:css`
// (src/index.css -> src/styles.css).
import css from "./styles.css?inline";

import FeedbackWidget from "./components/FeedbackWidget";

// Converts a hex color (#rrggbb / #rgb) to the "H S% L%" string that our CSS
// variables expect (they're consumed via hsl(var(--x))). Returns null on bad
// input so callers can skip setting the variable.
function hexToHSL(hex) {
  if (!hex) return null;
  let r = 0, g = 0, b = 0;
  if (hex.length === 4) {
    r = parseInt("0x" + hex[1] + hex[1]);
    g = parseInt("0x" + hex[2] + hex[2]);
    b = parseInt("0x" + hex[3] + hex[3]);
  } else if (hex.length === 7) {
    r = parseInt("0x" + hex[1] + hex[2]);
    g = parseInt("0x" + hex[3] + hex[4]);
    b = parseInt("0x" + hex[5] + hex[6]);
  } else {
    return null;
  }
  r /= 255; g /= 255; b /= 255;
  const cmin = Math.min(r, g, b);
  const cmax = Math.max(r, g, b);
  const delta = cmax - cmin;
  let h = 0, s = 0, l = 0;

  if (delta === 0) h = 0;
  else if (cmax === r) h = ((g - b) / delta) % 6;
  else if (cmax === g) h = (b - r) / delta + 2;
  else h = (r - g) / delta + 4;
  h = Math.round(h * 60);
  if (h < 0) h += 360;

  l = (cmax + cmin) / 2;
  s = delta === 0 ? 0 : delta / (1 - Math.abs(2 * l - 1));
  s = +(s * 100).toFixed(1);
  l = +(l * 100).toFixed(1);

  return `${h} ${s}% ${l}%`;
}

function App(props) {
  // The host element of the shadow root. We set inline CSS variables on it to
  // theme the widget per-instance without touching the compiled stylesheet.
  const shadowRef = useRef(null);

  // The dialog needs a portal target that lives *inside* the shadow root,
  // otherwise Radix portals it to document.body (outside the shadow DOM) and
  // our injected styles won't apply. We capture that node here.
  const [portalContainer, setPortalContainer] = useState(null);

  const [isOpen, setIsOpen] = useState(!!props.autoOpen);
  const lastOpenId = useRef(null);

  // Respond to programmatic open() calls from the host (main.jsx bumps _openId).
  useEffect(() => {
    if (props._openId && props._openId !== lastOpenId.current) {
      lastOpenId.current = props._openId;
      setIsOpen(true);
    }
  }, [props._openId]);

  // Apply per-instance theming via CSS variables on the shadow host element.
  useEffect(() => {
    const host = shadowRef.current;
    if (!host) return;
    if (props.primaryColor) {
      const hsl = hexToHSL(props.primaryColor);
      if (hsl) host.style.setProperty("--primary", hsl);
    }
  }, [props.primaryColor]);

  return (
    // react-shadow's root.div renders its children into an attached shadow root
    // on this element. `className` is applied to the host element.
    <root.div ref={shadowRef} className="shadowkit" style={{ position: "relative", zIndex: 99999 }}>
      {/* Inject the compiled, prefixed Tailwind CSS *inside* the shadow root. */}
      <style type="text/css">{css}</style>

      {/* Portal target for the dialog — must be inside the shadow root. */}
      <div ref={setPortalContainer} className="sdw-portal-root" />

      <FeedbackWidget
        {...props}
        isOpen={isOpen}
        setIsOpen={setIsOpen}
        portalContainer={portalContainer}
      />
    </root.div>
  );
}

export default App;
